# Generated by Django 3.2.6 on 2021-09-07 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('criado', models.DateField(auto_now_add=True, verbose_name='criacao')),
                ('atualizado', models.DateField(auto_now=True, verbose_name='atualizado')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clientes de Venda',
            },
        ),
        migrations.CreateModel(
            name='EntryType',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('criado', models.DateField(auto_now_add=True, verbose_name='criacao')),
                ('atualizado', models.DateField(auto_now=True, verbose_name='atualizado')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Tipo de lançamento',
                'verbose_name_plural': 'Tipos de lançamentos',
            },
        ),
        migrations.CreateModel(
            name='Meeiro',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('criado', models.DateField(auto_now_add=True, verbose_name='criacao')),
                ('atualizado', models.DateField(auto_now=True, verbose_name='atualizado')),
                ('name', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('rg', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Meeiro',
                'verbose_name_plural': 'Meeiros',
            },
        ),
        migrations.CreateModel(
            name='SalesEntry',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('criado', models.DateField(auto_now_add=True, verbose_name='criacao')),
                ('atualizado', models.DateField(auto_now=True, verbose_name='atualizado')),
                ('entry_date', models.DateField()),
                ('sales_price', models.FloatField()),
                ('buy_price', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('product', models.CharField(max_length=100)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
            options={
                'verbose_name': 'Lançamento de venda',
                'verbose_name_plural': 'Lançamentos de venda',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('criado', models.DateField(auto_now_add=True, verbose_name='criacao')),
                ('atualizado', models.DateField(auto_now=True, verbose_name='atualizado')),
                ('entry_date', models.DateField()),
                ('entry_value', models.FloatField()),
                ('description', models.CharField(max_length=500)),
                ('entry_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.entrytype')),
                ('meeiro_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.meeiro')),
            ],
            options={
                'verbose_name': 'Lançamento',
                'verbose_name_plural': 'Lançamentos de Meeiros',
            },
        ),
    ]
